// ── SwasthyaYoga — Pose Groups & Sequences ───────────────────────────────────
// Each group has multiple poses (sub-divided as requested)
// referenceImage: used to compare against user's captured photo

export const POSE_GROUPS = [
  {
    id: 'surya_namaskar',
    name: 'Surya Namaskar',
    emoji: '☀️',
    subtitle: '12 Poses • Full Body Flow',
    color: '#FF6D00',
    bgColor: '#FFF3E0',
    level: 'Intermediate',
    totalDuration: '10-15 min',
    description: 'Sun Salutation — a complete sequence of 12 poses done in flow',
    poses: [
      {
        id: 'sn_1', step: 1, name: 'Pranamasana', emoji: '🙏',
        instruction: 'Stand straight, bring palms together at chest. Feet together.',
        keyPoints: 'Spine straight, shoulders relaxed, palms together',
        duration: '30 sec',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Surya_namaskar.jpg/440px-Surya_namaskar.jpg',
      },
      {
        id: 'sn_2', step: 2, name: 'Hasta Uttanasana', emoji: '🙆',
        instruction: 'Raise arms up and bend slightly backward. Stretch fully.',
        keyPoints: 'Arms above head, slight backbend, look up',
        duration: '30 sec',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Surya_namaskar.jpg/440px-Surya_namaskar.jpg',
      },
      {
        id: 'sn_3', step: 3, name: 'Hasta Padasana', emoji: '🤸',
        instruction: 'Bend forward, touch the floor with palms. Legs straight.',
        keyPoints: 'Forehead near knees, palms flat on floor',
        duration: '30 sec',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Uttanasana_Yoga-Asana_Nina-Mel.jpg/440px-Uttanasana_Yoga-Asana_Nina-Mel.jpg',
      },
      {
        id: 'sn_4', step: 4, name: 'Ashwa Sanchalanasana', emoji: '🦵',
        instruction: 'Step right leg back into lunge. Left knee bent, look up.',
        keyPoints: 'Right leg straight back, left knee at 90°, chest open',
        duration: '30 sec',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Surya_namaskar.jpg/440px-Surya_namaskar.jpg',
      },
      {
        id: 'sn_5', step: 5, name: 'Dandasana', emoji: '📏',
        instruction: 'Bring left leg back. Body in straight plank position.',
        keyPoints: 'Body straight from head to heel, arms straight',
        duration: '30 sec',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Surya_namaskar.jpg/440px-Surya_namaskar.jpg',
      },
      {
        id: 'sn_6', step: 6, name: 'Ashtanga Namaskara', emoji: '🙇',
        instruction: 'Lower knees, chest, chin to floor. Hips slightly raised.',
        keyPoints: 'Eight points touching floor: toes, knees, chest, chin, hands',
        duration: '15 sec',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Surya_namaskar.jpg/440px-Surya_namaskar.jpg',
      },
      {
        id: 'sn_7', step: 7, name: 'Bhujangasana', emoji: '🐍',
        instruction: 'Lower hips, raise chest and head up. Cobra pose.',
        keyPoints: 'Elbows slightly bent, chest lifted, shoulders down',
        duration: '30 sec',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Bhujangasana_Yoga-Asana_Nina-Mel.jpg/440px-Bhujangasana_Yoga-Asana_Nina-Mel.jpg',
      },
      {
        id: 'sn_8', step: 8, name: 'Adho Mukha Svanasana', emoji: '🐕',
        instruction: 'Raise hips up, form an inverted V shape. Downward Dog.',
        keyPoints: 'Hips high, heels pressing down, head between arms',
        duration: '30 sec',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Adho_Mukha_Svanasana.jpg/440px-Adho_Mukha_Svanasana.jpg',
      },
      {
        id: 'sn_9', step: 9, name: 'Ashwa Sanchalanasana', emoji: '🦵',
        instruction: 'Step right foot forward into lunge again.',
        keyPoints: 'Right knee at 90°, left leg straight back, look up',
        duration: '30 sec',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Surya_namaskar.jpg/440px-Surya_namaskar.jpg',
      },
      {
        id: 'sn_10', step: 10, name: 'Hasta Padasana', emoji: '🤸',
        instruction: 'Bring left foot forward. Bend forward, touch floor.',
        keyPoints: 'Both feet together, palms on floor, knees straight',
        duration: '30 sec',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Uttanasana_Yoga-Asana_Nina-Mel.jpg/440px-Uttanasana_Yoga-Asana_Nina-Mel.jpg',
      },
      {
        id: 'sn_11', step: 11, name: 'Hasta Uttanasana', emoji: '🙆',
        instruction: 'Raise arms up and bend slightly backward again.',
        keyPoints: 'Arms stretched overhead, gentle backbend',
        duration: '30 sec',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Surya_namaskar.jpg/440px-Surya_namaskar.jpg',
      },
      {
        id: 'sn_12', step: 12, name: 'Pranamasana', emoji: '🙏',
        instruction: 'Return to prayer position. Exhale and relax.',
        keyPoints: 'Palms together, spine straight, breathe deeply',
        duration: '30 sec',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Surya_namaskar.jpg/440px-Surya_namaskar.jpg',
      },
    ],
  },

  {
    id: 'warrior_series',
    name: 'Warrior Series',
    emoji: '⚔️',
    subtitle: '3 Poses • Strength & Stability',
    color: '#C62828',
    bgColor: '#FFEBEE',
    level: 'Beginner',
    totalDuration: '5-8 min',
    description: 'Virabhadrasana series — builds strength, stamina and focus',
    poses: [
      {
        id: 'w_1', step: 1, name: 'Warrior I', emoji: '⚔️',
        instruction: 'Step one foot back. Front knee bent at 90°. Arms raised overhead.',
        keyPoints: 'Front knee over ankle, hips square forward, arms straight up',
        duration: '30 sec each side',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Virabhadrasana_I.jpg/440px-Virabhadrasana_I.jpg',
      },
      {
        id: 'w_2', step: 2, name: 'Warrior II', emoji: '🗡️',
        instruction: 'Open hips to the side. Arms stretched out parallel to floor.',
        keyPoints: 'Arms parallel to floor, gaze over front hand, hips open',
        duration: '30 sec each side',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Virabhadrasana_I.jpg/440px-Virabhadrasana_I.jpg',
      },
      {
        id: 'w_3', step: 3, name: 'Warrior III', emoji: '🦅',
        instruction: 'Balance on one leg. Lean forward, other leg and arms parallel to floor.',
        keyPoints: 'Body parallel to floor, standing leg straight, arms forward',
        duration: '20 sec each side',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Virabhadrasana_I.jpg/440px-Virabhadrasana_I.jpg',
      },
    ],
  },

  {
    id: 'balancing_series',
    name: 'Balance Series',
    emoji: '🌳',
    subtitle: '4 Poses • Focus & Stability',
    color: '#2E7D32',
    bgColor: '#E8F5E9',
    level: 'Beginner',
    totalDuration: '6-10 min',
    description: 'Balance poses that improve concentration and body awareness',
    poses: [
      {
        id: 'bal_1', step: 1, name: 'Tree Pose', emoji: '🌳',
        instruction: 'Stand on one leg. Place other foot on inner thigh. Palms together.',
        keyPoints: 'Standing leg straight, foot on thigh (not knee), arms up or prayer',
        duration: '30 sec each side',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Vrikshasana_Yoga-Asana_Nina-Mel.jpg/440px-Vrikshasana_Yoga-Asana_Nina-Mel.jpg',
      },
      {
        id: 'bal_2', step: 2, name: 'Eagle Pose', emoji: '🦅',
        instruction: 'Cross one leg over other. Wrap arms. Sink down slightly.',
        keyPoints: 'Arms wrapped and lifted, knees bent, gaze forward',
        duration: '30 sec each side',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Garudasana_Yoga-Asana_Nina-Mel.jpg/440px-Garudasana_Yoga-Asana_Nina-Mel.jpg',
      },
      {
        id: 'bal_3', step: 3, name: 'Dancer Pose', emoji: '💃',
        instruction: 'Stand on one leg. Hold other ankle behind you. Lean forward.',
        keyPoints: 'Front arm extended, back leg raised high, chest open',
        duration: '20 sec each side',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Natarajasana_Yoga-Asana_Nina-Mel.jpg/440px-Natarajasana_Yoga-Asana_Nina-Mel.jpg',
      },
      {
        id: 'bal_4', step: 4, name: 'Mountain Pose', emoji: '🧍',
        instruction: 'Stand perfectly straight. Feet together. Arms at sides.',
        keyPoints: 'Feet together, spine tall, chin level, arms relaxed',
        duration: '1 min',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Tadasana_Yoga-Asana_Nina-Mel.jpg/440px-Tadasana_Yoga-Asana_Nina-Mel.jpg',
      },
    ],
  },

  {
    id: 'backbend_series',
    name: 'Backbend Series',
    emoji: '🌉',
    subtitle: '4 Poses • Spine Health',
    color: '#6A1B9A',
    bgColor: '#F3E5F5',
    level: 'Beginner',
    totalDuration: '8-12 min',
    description: 'Opens the chest, strengthens spine and improves flexibility',
    poses: [
      {
        id: 'bb_1', step: 1, name: 'Cobra Pose', emoji: '🐍',
        instruction: 'Lie face down. Place palms near shoulders. Raise chest up.',
        keyPoints: 'Elbows slightly bent, shoulders away from ears, hips on floor',
        duration: '30 sec',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Bhujangasana_Yoga-Asana_Nina-Mel.jpg/440px-Bhujangasana_Yoga-Asana_Nina-Mel.jpg',
      },
      {
        id: 'bb_2', step: 2, name: 'Bridge Pose', emoji: '🌉',
        instruction: 'Lie on back. Bend knees. Lift hips up toward ceiling.',
        keyPoints: 'Feet flat on floor, knees over ankles, hips high',
        duration: '30-60 sec',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Setubandhasana_yoga_pose.jpg/440px-Setubandhasana_yoga_pose.jpg',
      },
      {
        id: 'bb_3', step: 3, name: 'Bow Pose', emoji: '🏹',
        instruction: 'Lie face down. Grab ankles. Lift chest and legs simultaneously.',
        keyPoints: 'Thighs off ground, chest lifted, arms straight',
        duration: '20-30 sec',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Dhanurasana_Yoga-Asana_Nina-Mel.jpg/440px-Dhanurasana_Yoga-Asana_Nina-Mel.jpg',
      },
      {
        id: 'bb_4', step: 4, name: "Child's Pose", emoji: '🙇',
        instruction: 'Sit back on heels. Fold forward. Arms extended or by sides.',
        keyPoints: 'Forehead on floor, hips on heels, arms relaxed',
        duration: '1-3 min',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Childs_pose.jpg/440px-Childs_pose.jpg',
      },
    ],
  },

  {
    id: 'relaxation_series',
    name: 'Relaxation Series',
    emoji: '😌',
    subtitle: '3 Poses • Stress Relief',
    color: '#00838F',
    bgColor: '#E0F7FA',
    level: 'Beginner',
    totalDuration: '15-20 min',
    description: 'Deep relaxation poses to calm the mind and restore energy',
    poses: [
      {
        id: 'rel_1', step: 1, name: 'Legs Up The Wall', emoji: '🦵',
        instruction: 'Lie on back near wall. Raise legs up against wall.',
        keyPoints: 'Legs straight up, back flat, arms relaxed at sides',
        duration: '5-15 min',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Viparita_Karani_Yoga-Asana_Nina-Mel.jpg/440px-Viparita_Karani_Yoga-Asana_Nina-Mel.jpg',
      },
      {
        id: 'rel_2', step: 2, name: 'Butterfly Pose', emoji: '🦋',
        instruction: 'Sit with soles of feet together. Gently flap knees.',
        keyPoints: 'Spine straight, feet close to body, knees dropping down',
        duration: '1-5 min',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Bound_angle_pose.jpg/440px-Bound_angle_pose.jpg',
      },
      {
        id: 'rel_3', step: 3, name: 'Corpse Pose', emoji: '😌',
        instruction: 'Lie flat on back. Arms by sides. Close eyes. Breathe slowly.',
        keyPoints: 'Complete stillness, body fully relaxed, natural breathing',
        duration: '5-10 min',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Shavasana_2.jpg/440px-Shavasana_2.jpg',
      },
    ],
  },

  {
    id: 'breathing_series',
    name: 'Pranayama',
    emoji: '🌬️',
    subtitle: '3 Techniques • Breathwork',
    color: '#1565C0',
    bgColor: '#E3F2FD',
    level: 'Beginner',
    totalDuration: '10-15 min',
    description: 'Breathing techniques to balance energy and calm the nervous system',
    poses: [
      {
        id: 'pr_1', step: 1, name: 'Alternate Nostril', emoji: '🌬️',
        instruction: 'Close right nostril, inhale left. Close left, exhale right. Repeat.',
        keyPoints: 'Sit straight, use right hand, slow even breaths',
        duration: '5-10 min',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Pranayama.jpg/440px-Pranayama.jpg',
      },
      {
        id: 'pr_2', step: 2, name: 'Bhramari', emoji: '🐝',
        instruction: 'Close ears with thumbs. Inhale. Exhale with humming sound.',
        keyPoints: 'Eyes closed, thumbs on ears, fingers on face, hum smoothly',
        duration: '5 min',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Pranayama.jpg/440px-Pranayama.jpg',
      },
      {
        id: 'pr_3', step: 3, name: 'Kapalabhati', emoji: '💨',
        instruction: 'Forceful exhales through nose in quick succession.',
        keyPoints: 'Passive inhale, forceful exhale, belly pumping',
        duration: '3-5 min',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Pranayama.jpg/440px-Pranayama.jpg',
      },
    ],
  },
];

export const GROUP_LEVELS = {
  Beginner:     { bg: '#E8F5E9', text: '#2E7D32' },
  Intermediate: { bg: '#FFF3E0', text: '#E65100' },
  Advanced:     { bg: '#FFEBEE', text: '#C62828' },
};