// ── Pose of the Day — Asana List ─────────────────────────────────────────────
// 20 safe, well-known yoga poses with Wikipedia images

export const POSE_LIST = [
  {
    id: 'tadasana',
    sanskritName: 'Tadasana',
    name: { en: 'Mountain Pose', te: 'తాడాసన', hi: 'ताड़ासन' },
    level: 'Beginner',
    duration: '30 sec',
    emoji: '🧍',
    benefit: { en: 'Improves posture and balance', te: 'భంగిమ మెరుగుపరుస్తుంది', hi: 'मुद्रा और संतुलन सुधारता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Tadasana_Yoga-Asana_Nina-Mel.jpg/440px-Tadasana_Yoga-Asana_Nina-Mel.jpg',
    category: 'Standing',
  },
  {
    id: 'vrikshasana',
    sanskritName: 'Vrikshasana',
    name: { en: 'Tree Pose', te: 'వృక్షాసన', hi: 'वृक्षासन' },
    level: 'Beginner',
    duration: '30 sec each side',
    emoji: '🌳',
    benefit: { en: 'Builds balance and concentration', te: 'సమతుల్యత మరియు ఏకాగ్రత పెంచుతుంది', hi: 'संतुलन और एकाग्रता बढ़ाता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Vrikshasana_Yoga-Asana_Nina-Mel.jpg/440px-Vrikshasana_Yoga-Asana_Nina-Mel.jpg',
    category: 'Balancing',
  },
  {
    id: 'bhujangasana',
    sanskritName: 'Bhujangasana',
    name: { en: 'Cobra Pose', te: 'భుజంగాసన', hi: 'भुजंगासन' },
    level: 'Beginner',
    duration: '30 sec',
    emoji: '🐍',
    benefit: { en: 'Strengthens spine and opens chest', te: 'వెన్నెముక బలపరుస్తుంది', hi: 'रीढ़ मजबूत करता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Bhujangasana_Yoga-Asana_Nina-Mel.jpg/440px-Bhujangasana_Yoga-Asana_Nina-Mel.jpg',
    category: 'Backbend',
  },
  {
    id: 'balasana',
    sanskritName: 'Balasana',
    name: { en: "Child's Pose", te: 'బాలాసన', hi: 'बालासन' },
    level: 'Beginner',
    duration: '1-3 min',
    emoji: '🙇',
    benefit: { en: 'Relieves stress and back pain', te: 'ఒత్తిడి మరియు వీపు నొప్పి తగ్గిస్తుంది', hi: 'तनाव और पीठ दर्द से राहत' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Childs_pose.jpg/440px-Childs_pose.jpg',
    category: 'Resting',
  },
  {
    id: 'virabhadrasana1',
    sanskritName: 'Virabhadrasana',
    name: { en: 'Warrior I', te: 'వీరభద్రాసన I', hi: 'वीरभद्रासन I' },
    level: 'Beginner',
    duration: '30 sec each side',
    emoji: '⚔️',
    benefit: { en: 'Strengthens legs and opens hips', te: 'కాళ్ళు బలపరుస్తుంది', hi: 'पैर मजबूत करता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Virabhadrasana_I.jpg/440px-Virabhadrasana_I.jpg',
    category: 'Standing',
  },
  {
    id: 'trikonasana',
    sanskritName: 'Trikonasana',
    name: { en: 'Triangle Pose', te: 'త్రికోణాసన', hi: 'त्रिकोणासन' },
    level: 'Beginner',
    duration: '30 sec each side',
    emoji: '📐',
    benefit: { en: 'Stretches legs and spine', te: 'కాళ్ళు మరియు వెన్నెముక సాగదీస్తుంది', hi: 'पैर और रीढ़ खींचता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Trikonasana_Yoga-Asana_Nina-Mel.jpg/440px-Trikonasana_Yoga-Asana_Nina-Mel.jpg',
    category: 'Standing',
  },
  {
    id: 'dhanurasana',
    sanskritName: 'Dhanurasana',
    name: { en: 'Bow Pose', te: 'ధనురాసన', hi: 'धनुरासन' },
    level: 'Intermediate',
    duration: '20-30 sec',
    emoji: '🏹',
    benefit: { en: 'Stimulates pancreas, helps digestion', te: 'అగ్న్యాశయాన్ని ఉత్తేజపరుస్తుంది', hi: 'अग्न्याशय को उत्तेजित करता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Dhanurasana_Yoga-Asana_Nina-Mel.jpg/440px-Dhanurasana_Yoga-Asana_Nina-Mel.jpg',
    category: 'Backbend',
  },
  {
    id: 'paschimottanasana',
    sanskritName: 'Paschimottanasana',
    name: { en: 'Seated Forward Bend', te: 'పశ్చిమోత్తానాసన', hi: 'पश्चिमोत्तानासन' },
    level: 'Beginner',
    duration: '1-3 min',
    emoji: '🙆',
    benefit: { en: 'Stretches hamstrings and back', te: 'వెనక కండరాలు సాగదీస్తుంది', hi: 'हैमस्ट्रिंग और पीठ खींचता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Paschimottanasana_Yoga-Asana_Nina-Mel.jpg/440px-Paschimottanasana_Yoga-Asana_Nina-Mel.jpg',
    category: 'Forward Bend',
  },
  {
    id: 'setu_bandhasana',
    sanskritName: 'Setu Bandhasana',
    name: { en: 'Bridge Pose', te: 'సేతు బంధాసన', hi: 'सेतु बंधासन' },
    level: 'Beginner',
    duration: '30-60 sec',
    emoji: '🌉',
    benefit: { en: 'Strengthens back and glutes', te: 'వీపు మరియు నిమ్నాంగం బలపరుస్తుంది', hi: 'पीठ और ग्लूट्स मजबूत करता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Setubandhasana_yoga_pose.jpg/440px-Setubandhasana_yoga_pose.jpg',
    category: 'Backbend',
  },
  {
    id: 'shavasana',
    sanskritName: 'Shavasana',
    name: { en: 'Corpse Pose', te: 'శవాసన', hi: 'शवासन' },
    level: 'Beginner',
    duration: '5-10 min',
    emoji: '😌',
    benefit: { en: 'Deep relaxation, reduces stress', te: 'లోతైన విశ్రాంతి, ఒత్తిడి తగ్గిస్తుంది', hi: 'गहरी छूट, तनाव कम करता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Shavasana_2.jpg/440px-Shavasana_2.jpg',
    category: 'Resting',
  },
  {
    id: 'uttanasana',
    sanskritName: 'Uttanasana',
    name: { en: 'Standing Forward Fold', te: 'ఉత్తానాసన', hi: 'उत्तानासन' },
    level: 'Beginner',
    duration: '30 sec - 1 min',
    emoji: '🤸',
    benefit: { en: 'Relieves tension, calms mind', te: 'ఉద్రిక్తతను తగ్గిస్తుంది', hi: 'तनाव से राहत, मन शांत' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Uttanasana_Yoga-Asana_Nina-Mel.jpg/440px-Uttanasana_Yoga-Asana_Nina-Mel.jpg',
    category: 'Forward Bend',
  },
  {
    id: 'viparita_karani',
    sanskritName: 'Viparita Karani',
    name: { en: 'Legs Up The Wall', te: 'విపరీత కరణి', hi: 'विपरीत करणी' },
    level: 'Beginner',
    duration: '5-15 min',
    emoji: '🦵',
    benefit: { en: 'Reduces anxiety, improves circulation', te: 'ఆందోళన తగ్గిస్తుంది', hi: 'चिंता कम करता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Viparita_Karani_Yoga-Asana_Nina-Mel.jpg/440px-Viparita_Karani_Yoga-Asana_Nina-Mel.jpg',
    category: 'Inversion',
  },
  {
    id: 'garudasana',
    sanskritName: 'Garudasana',
    name: { en: 'Eagle Pose', te: 'గరుడాసన', hi: 'गरुड़ासन' },
    level: 'Intermediate',
    duration: '30 sec each side',
    emoji: '🦅',
    benefit: { en: 'Improves focus and balance', te: 'ఏకాగ్రత మరియు సమతుల్యత మెరుగుపరుస్తుంది', hi: 'एकाग्रता और संतुलन सुधारता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Garudasana_Yoga-Asana_Nina-Mel.jpg/440px-Garudasana_Yoga-Asana_Nina-Mel.jpg',
    category: 'Balancing',
  },
  {
    id: 'baddha_konasana',
    sanskritName: 'Baddha Konasana',
    name: { en: 'Butterfly Pose', te: 'బద్ధ కోణాసన', hi: 'बद्ध कोणासन' },
    level: 'Beginner',
    duration: '1-5 min',
    emoji: '🦋',
    benefit: { en: 'Opens hips, good for PCOD', te: 'తొడలు తెరుస్తుంది, PCOD కి మంచిది', hi: 'कूल्हे खोलता है, PCOD के लिए अच्छा' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Bound_angle_pose.jpg/440px-Bound_angle_pose.jpg',
    category: 'Seated',
  },
  {
    id: 'adho_mukha',
    sanskritName: 'Adho Mukha Svanasana',
    name: { en: 'Downward Dog', te: 'అధో ముఖ శ్వానాసన', hi: 'अधो मुख श्वानासन' },
    level: 'Beginner',
    duration: '1-3 min',
    emoji: '🐕',
    benefit: { en: 'Full body stretch, energizes', te: 'శరీరం మొత్తం సాగదీస్తుంది', hi: 'पूरे शरीर को खींचता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Adho_Mukha_Svanasana.jpg/440px-Adho_Mukha_Svanasana.jpg',
    category: 'Standing',
  },
  {
    id: 'natarajasana',
    sanskritName: 'Natarajasana',
    name: { en: 'Dancer Pose', te: 'నటరాజాసన', hi: 'नटराजासन' },
    level: 'Intermediate',
    duration: '20-30 sec each side',
    emoji: '💃',
    benefit: { en: 'Improves balance and flexibility', te: 'సమతుల్యత మరియు వశ్యత మెరుగుపరుస్తుంది', hi: 'संतुलन और लचीलापन सुधारता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Natarajasana_Yoga-Asana_Nina-Mel.jpg/440px-Natarajasana_Yoga-Asana_Nina-Mel.jpg',
    category: 'Balancing',
  },
  {
    id: 'utkatasana',
    sanskritName: 'Utkatasana',
    name: { en: 'Chair Pose', te: 'ఉత్కటాసన', hi: 'उत्कटासन' },
    level: 'Beginner',
    duration: '30 sec - 1 min',
    emoji: '🪑',
    benefit: { en: 'Builds leg strength and stamina', te: 'కాళ్ళ బలం పెంచుతుంది', hi: 'पैर की ताकत बढ़ाता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Utkatasana_Yoga-Asana_Nina-Mel.jpg/440px-Utkatasana_Yoga-Asana_Nina-Mel.jpg',
    category: 'Standing',
  },
  {
    id: 'virasana',
    sanskritName: 'Virasana',
    name: { en: 'Hero Pose', te: 'వీరాసన', hi: 'वीरासन' },
    level: 'Beginner',
    duration: '1-5 min',
    emoji: '🦸',
    benefit: { en: 'Stretches knees and improves posture', te: 'మోకాళ్ళు సాగదీస్తుంది', hi: 'घुटनों को खींचता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Virasana_Yoga-Asana_Nina-Mel.jpg/440px-Virasana_Yoga-Asana_Nina-Mel.jpg',
    category: 'Seated',
  },
  {
    id: 'anulom_vilom',
    sanskritName: 'Pranayama',
    name: { en: 'Alternate Nostril Breathing', te: 'అనులోమ విలోమ', hi: 'अनुलोम विलोम' },
    level: 'Beginner',
    duration: '5-10 min',
    emoji: '🌬️',
    benefit: { en: 'Balances nervous system, reduces BP', te: 'నాడీ వ్యవస్థను సమతుల్యం చేస్తుంది', hi: 'तंत्रिका तंत्र संतुलित करता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Pranayama.jpg/440px-Pranayama.jpg',
    category: 'Breathing',
  },
  {
    id: 'surya_namaskar',
    sanskritName: 'Surya Namaskar',
    name: { en: 'Sun Salutation', te: 'సూర్య నమస్కారం', hi: 'सूर्य नमस्कार' },
    level: 'Intermediate',
    duration: '5-10 min',
    emoji: '☀️',
    benefit: { en: 'Full body workout, 12 poses in flow', te: 'పూర్తి శరీర వ్యాయామం', hi: 'पूर्ण शरीर व्यायाम' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Surya_namaskar.jpg/440px-Surya_namaskar.jpg',
    category: 'Sequence',
  },
  {
    id: 'sukhasana',
    sanskritName: 'Sukhasana',
    name: { en: 'Easy Pose', te: 'సుఖాసన', hi: 'सुखासन' },
    level: 'Beginner',
    duration: '1-5 min',
    emoji: '🧘',
    benefit: { en: 'Calms mind, improves posture', te: 'మనసు శాంతిస్తుంది, భంగిమ మెరుగవుతుంది', hi: 'मन शांत, मुद्रा सुधरती है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Sukhasana_Yoga-Asana_Nina-Mel.jpg/440px-Sukhasana_Yoga-Asana_Nina-Mel.jpg',
    category: 'Seated',
  },
  {
    id: 'vajrasana',
    sanskritName: 'Vajrasana',
    name: { en: 'Thunderbolt Pose', te: 'వజ్రాసన', hi: 'वज्रासन' },
    level: 'Beginner',
    duration: '5-10 min after meals',
    emoji: '⚡',
    benefit: { en: 'Best pose after eating, aids digestion', te: 'భోజనం తర్వాత చేయడానికి అత్యుత్తమం, జీర్ణక్రియ మెరుగుపరుస్తుంది', hi: 'खाने के बाद सबसे अच्छा, पाचन सुधारता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Vajrasana_Yoga-Asana_Nina-Mel.jpg/440px-Vajrasana_Yoga-Asana_Nina-Mel.jpg',
    category: 'Seated',
  },
  {
    id: 'padmasana',
    sanskritName: 'Padmasana',
    name: { en: 'Lotus Pose', te: 'పద్మాసన', hi: 'पद्मासन' },
    level: 'Intermediate',
    duration: '1-5 min',
    emoji: '🪷',
    benefit: { en: 'Deepens meditation, opens hips', te: 'ధ్యానాన్ని లోతుగా చేస్తుంది, తొడలు తెరుస్తుంది', hi: 'ध्यान गहरा करता है, कूल्हे खोलता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Padmasana_Yoga-Asana_Nina-Mel.jpg/440px-Padmasana_Yoga-Asana_Nina-Mel.jpg',
    category: 'Seated',
  },
  {
    id: 'ardha_matsyendrasana',
    sanskritName: 'Ardha Matsyendrasana',
    name: { en: 'Seated Spinal Twist', te: 'అర్ధ మత్స్యేంద్రాసన', hi: 'अर्ध मत्स्येंद्रासन' },
    level: 'Beginner',
    duration: '30 sec each side',
    emoji: '🌀',
    benefit: { en: 'Relieves back pain, improves digestion', te: 'వీపు నొప్పి తగ్గిస్తుంది, జీర్ణక్రియ మెరుగుపరుస్తుంది', hi: 'पीठ दर्द कम करता है, पाचन सुधारता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Ardha_Matsyendrasana_Yoga-Asana_Nina-Mel.jpg/440px-Ardha_Matsyendrasana_Yoga-Asana_Nina-Mel.jpg',
    category: 'Seated',
  },
  {
    id: 'gomukhasana',
    sanskritName: 'Gomukhasana',
    name: { en: 'Cow Face Pose', te: 'గోముఖాసన', hi: 'गोमुखासन' },
    level: 'Beginner',
    duration: '1 min each side',
    emoji: '🐄',
    benefit: { en: 'Opens shoulders, relieves tension', te: 'భుజాలు తెరుస్తుంది, ఒత్తిడి తగ్గిస్తుంది', hi: 'कंधे खोलता है, तनाव कम करता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Gomukhasana_Yoga-Asana_Nina-Mel.jpg/440px-Gomukhasana_Yoga-Asana_Nina-Mel.jpg',
    category: 'Seated',
  },
  {
    id: 'janu_sirsasana',
    sanskritName: 'Janu Sirsasana',
    name: { en: 'Head to Knee Pose', te: 'జాను శీర్షాసన', hi: 'जानु शीर्षासन' },
    level: 'Beginner',
    duration: '1 min each side',
    emoji: '🦵',
    benefit: { en: 'Stretches hamstrings, calms mind', te: 'వెనక కండరాలు సాగదీస్తుంది, మనసు శాంతిస్తుంది', hi: 'हैमस्ट्रिंग खींचता है, मन शांत करता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Janu_Sirsasana_Yoga-Asana_Nina-Mel.jpg/440px-Janu_Sirsasana_Yoga-Asana_Nina-Mel.jpg',
    category: 'Seated',
  },
  {
    id: 'mandukasana',
    sanskritName: 'Mandukasana',
    name: { en: 'Frog Pose', te: 'మండూకాసన', hi: 'मंडूकासन' },
    level: 'Beginner',
    duration: '30-60 sec',
    emoji: '🐸',
    benefit: { en: 'Good for diabetes, massages pancreas', te: 'మధుమేహానికి మంచిది, అగ్న్యాశయాన్ని మసాజ్ చేస్తుంది', hi: 'मधुमेह के लिए अच्छा, अग्न्याशय की मालिश' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Mandukasana.jpg/440px-Mandukasana.jpg',
    category: 'Seated',
  },
  {
    id: 'shashankasana',
    sanskritName: 'Shashankasana',
    name: { en: 'Rabbit Pose', te: 'శశాంకాసన', hi: 'शशांकासन' },
    level: 'Beginner',
    duration: '1-3 min',
    emoji: '🐇',
    benefit: { en: 'Relieves stress, stretches back gently', te: 'ఒత్తిడి తగ్గిస్తుంది, వీపును మెల్లగా సాగదీస్తుంది', hi: 'तनाव कम करता है, पीठ को धीरे से खींचता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Shashankasana.jpg/440px-Shashankasana.jpg',
    category: 'Seated',
  },
  {
    id: 'kapalbhati',
    sanskritName: 'Kapalbhati Pranayama',
    name: { en: 'Skull Shining Breath', te: 'కపాలభాతి', hi: 'कपालभाति' },
    level: 'Beginner',
    duration: '5 min',
    emoji: '💨',
    benefit: { en: 'Energizes body, cleanses lungs, reduces belly fat', te: 'శరీరానికి శక్తి ఇస్తుంది, పొట్ట కొవ్వు తగ్గిస్తుంది', hi: 'शरीर को ऊर्जा देता है, पेट की चर्बी कम करता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Pranayama.jpg/440px-Pranayama.jpg',
    category: 'Breathing',
  },
  {
    id: 'nadi_shodhana',
    sanskritName: 'Nadi Shodhana',
    name: { en: 'Channel Cleaning Breath', te: 'నాడీ శోధన', hi: 'नाड़ी शोधन' },
    level: 'Beginner',
    duration: '5-10 min',
    emoji: '🌬️',
    benefit: { en: 'Reduces anxiety, balances left and right brain', te: 'ఆందోళన తగ్గిస్తుంది, మెదడు రెండు భాగాలను సమతుల్యం చేస్తుంది', hi: 'चिंता कम करता है, मस्तिष्क संतुलित करता है' },
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Pranayama.jpg/440px-Pranayama.jpg',
    category: 'Breathing',
  },
];

export const CATEGORIES = ['All', 'Seated', 'Breathing', 'Standing', 'Balancing', 'Backbend', 'Forward Bend', 'Resting', 'Inversion', 'Sequence'];

export const LEVEL_COLORS = {
  Beginner:     { bg: '#E8F5E9', text: '#2E7D32' },
  Intermediate: { bg: '#FFF3E0', text: '#E65100' },
  Advanced:     { bg: '#FFEBEE', text: '#C62828' },
};