// ── SwasthyaYoga Health Data ──────────────────────────────────────────────────
// Trusted sources: AYUSH Ministry, Yoga Journal, Art of Living, Mayo Clinic
// All content in English, Telugu (తెలుగు), Hindi (हिंदी)

export const CONDITIONS = [
  {
    id: 'back_pain',
    emoji: '🔙',
    color: '#E53935',
    lightColor: '#FFEBEE',
    name: { en: 'Back Pain', te: 'వీపు నొప్పి', hi: 'पीठ दर्द' },
    desc: {
      en: 'Yoga therapy for lower and upper back pain relief',
      te: 'వీపు నొప్పి నివారణకు యోగా చికిత్స',
      hi: 'पीठ दर्द से राहत के लिए योग चिकित्सा',
    },
    asanas: [
      {
        id: 'balasana',
        sanskritName: 'Balasana',
        name: { en: "Child's Pose (Balasana)", te: 'బాలాసన', hi: 'बालासन' },
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Childs_pose.jpg/640px-Childs_pose.jpg',
        duration: { en: '5 min', te: '5 నిమిషాలు', hi: '5 मिनट' },
        steps: {
          en: ['Kneel on the mat with big toes touching', 'Sit back on your heels and separate knees hip-width', 'Extend arms forward, lower forehead to mat', 'Breathe deeply, hold 1–3 minutes', 'Slowly rise back up on inhale'],
          te: ['మోకాళ్ళపై కూర్చుని పెద్ద వేళ్ళు తాకించండి', 'మోకాళ్ళను వెడల్పు చేసి వెనక్కి కూర్చోండి', 'చేతులు ముందుకు చాచి నుదుటి నేలకు తాకించండి', 'లోతుగా శ్వాసించి 1-3 నిమిషాలు ఉండండి', 'శ్వాస తీసుకుంటూ మెల్లగా లేవండి'],
          hi: ['घुटनों पर बैठें, अंगूठे छुएं', 'घुटने कूल्हे-चौड़ाई पर फैलाएं', 'हाथ आगे फैलाएं, माथा जमीन पर', 'गहरी सांस लें, 1-3 मिनट रहें', 'सांस लेते हुए धीरे उठें'],
        },
        benefit: { en: 'Gently stretches lower back and hips', te: 'వీపు క్రింది భాగాన్ని సాగదీస్తుంది', hi: 'पीठ के निचले हिस्से को खींचता है' },
      },
      {
        id: 'cat_cow',
        sanskritName: 'Marjaryasana',
        name: { en: 'Cat-Cow Pose (Marjaryasana)', te: 'మార్జారాసన', hi: 'मार्जरासन' },
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Cat-Cow_Pose.jpg/640px-Cat-Cow_Pose.jpg',
        duration: { en: '3 min', te: '3 నిమిషాలు', hi: '3 मिनट' },
        steps: {
          en: ['Start on hands and knees, wrists under shoulders', 'Inhale — drop belly, lift head and tailbone (Cow)', 'Exhale — round spine, tuck chin and pelvis (Cat)', 'Flow between both for 10–15 cycles', 'Move slowly and breathe deeply'],
          te: ['చేతులు మోకాళ్ళపై ప్రారంభించండి', 'శ్వాస తీసుకుంటూ పొట్ట వంచి తల పైకి ఎత్తండి', 'శ్వాస వదులుతూ వెన్నెముక వంచి తల వంచండి', '10-15 సార్లు పునరావృతం చేయండి', 'మెల్లగా కదలండి'],
          hi: ['हाथों और घुटनों पर शुरू करें', 'सांस लेते हुए पेट नीचे करें (गाय)', 'सांस छोड़ते हुए रीढ़ गोल करें (बिल्ली)', '10-15 बार दोहराएं', 'धीरे-धीरे और गहरी सांस लें'],
        },
        benefit: { en: 'Improves spinal flexibility and relieves tension', te: 'వెన్నెముక వశ్యతను మెరుగుపరుస్తుంది', hi: 'रीढ़ की लचक बढ़ाता है' },
      },
      {
        id: 'bhujangasana',
        sanskritName: 'Bhujangasana',
        name: { en: 'Cobra Pose (Bhujangasana)', te: 'భుజంగాసన', hi: 'भुजंगासन' },
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Bhujangasana_Yoga-Asana_Nina-Mel.jpg/640px-Bhujangasana_Yoga-Asana_Nina-Mel.jpg',
        duration: { en: '2 min', te: '2 నిమిషాలు', hi: '2 मिनट' },
        steps: {
          en: ['Lie face down, palms under shoulders', 'Press tops of feet into mat', 'Inhale — lift chest off the floor', 'Keep elbows slightly bent, shoulders away from ears', 'Hold 30 seconds, exhale and lower'],
          te: ['పొట్ట నేలకు ఆనించి చేతులు భుజాల కింద ఉంచండి', 'పాదాల పై భాగం నేలకు తాకించండి', 'శ్వాస తీసుకుంటూ గుండె నేల నుండి పైకి ఎత్తండి', '30 సెకన్లు ఉండండి', 'శ్వాస వదులుతూ వంచండి'],
          hi: ['पेट के बल लेटें, हथेलियां कंधों के नीचे', 'पैरों के ऊपरी हिस्से से जमीन दबाएं', 'सांस लेते हुए सीना उठाएं', '30 सेकंड रहें, सांस छोड़ते हुए नीचे आएं'],
        },
        benefit: { en: 'Strengthens spine and opens chest', te: 'వెన్నెముకను బలపరుస్తుంది', hi: 'रीढ़ मजबूत होती है' },
      },
      {
        id: 'setu_bandha',
        sanskritName: 'Setu Bandhasana',
        name: { en: 'Bridge Pose (Setu Bandhasana)', te: 'సేతు బంధాసన', hi: 'सेतु बंधासन' },
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Setubandhasana_yoga_pose.jpg/640px-Setubandhasana_yoga_pose.jpg',
        duration: { en: '3 min', te: '3 నిమిషాలు', hi: '3 मिनट' },
        steps: {
          en: ['Lie on back, knees bent, feet flat on floor', 'Arms alongside body, palms down', 'Inhale — press feet into floor, lift hips', 'Clasp hands under your back', 'Hold 30–60 seconds, slowly lower on exhale'],
          te: ['వెల్లకిలా పడుకుని మోకాళ్ళు వంచండి', 'చేతులు ప్రక్కన ఉంచండి', 'శ్వాస తీసుకుంటూ పోపులు పైకి ఎత్తండి', '30-60 సెకన్లు ఉండి వదలండి'],
          hi: ['पीठ पर लेटें, घुटने मोड़ें', 'सांस लेते हुए कूल्हे ऊपर उठाएं', '30-60 सेकंड रहें', 'सांस छोड़ते हुए नीचे आएं'],
        },
        benefit: { en: 'Strengthens back muscles and glutes', te: 'వీపు కండరాలను బలపరుస్తుంది', hi: 'पीठ की मांसपेशियां मजबूत होती हैं' },
      },
    ],
    foodEat: [
      { name: { en: 'Turmeric Milk', te: 'పసుపు పాలు', hi: 'हल्दी दूध' }, image: 'https://images.unsplash.com/photo-1615485500704-8e3b85efb8f0?w=200', emoji: '🥛' },
      { name: { en: 'Ginger Tea', te: 'అల్లం టీ', hi: 'अदरक चाय' }, image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=200', emoji: '🍵' },
      { name: { en: 'Spinach', te: 'పాలకూర', hi: 'पालक' }, image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=200', emoji: '🥬' },
      { name: { en: 'Walnuts', te: 'అక్రోట్లు', hi: 'अखरोट' }, image: 'https://images.unsplash.com/photo-1563412885-139e4045ec52?w=200', emoji: '🥜' },
      { name: { en: 'Banana', te: 'అరటి పండు', hi: 'केला' }, image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=200', emoji: '🍌' },
    ],
    foodAvoid: [
      { name: { en: 'Fried Foods', te: 'వేయించిన పదార్థాలు', hi: 'तले हुए खाद्य पदार्थ' }, image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=200', emoji: '🍟' },
      { name: { en: 'Cold Drinks', te: 'చల్లని పానీయాలు', hi: 'ठंडे पेय' }, image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=200', emoji: '🥤' },
      { name: { en: 'Processed Food', te: 'ప్రాసెస్ చేసిన ఆహారం', hi: 'प्रसंस्कृत भोजन' }, image: 'https://images.unsplash.com/photo-1527459822135-9a2a6c399f3f?w=200', emoji: '🍕' },
    ],
    dos: {
      en: ['Sleep on a firm mattress', 'Use a pillow between knees while sleeping', 'Do yoga every morning for 20 minutes', 'Maintain good posture while sitting', 'Apply warm compress before yoga'],
      te: ['గట్టి పరుపుపై నిద్రించండి', 'నిద్రించేటప్పుడు మోకాళ్ళ మధ్య దిండు పెట్టండి', 'ప్రతి రోజు 20 నిమిషాలు యోగా చేయండి', 'కూర్చున్నప్పుడు సరైన భంగిమలో ఉండండి', 'యోగా ముందు వేడి కాంప్రెస్ వాడండి'],
      hi: ['कठोर गद्दे पर सोएं', 'सोते समय घुटनों के बीच तकिया रखें', 'रोज सुबह 20 मिनट योग करें', 'बैठते समय सही मुद्रा बनाए रखें', 'योग से पहले गर्म सेंक लगाएं'],
    },
    donts: {
      en: ['Avoid heavy lifting', 'Don\'t sit for long hours without break', 'Avoid high heels', 'Don\'t sleep on your stomach', 'Avoid sudden twisting movements'],
      te: ['భారమైన వస్తువులు ఎత్తకండి', 'విరామం లేకుండా గంటల తరబడి కూర్చోకండి', 'హై హీల్స్ ధరించకండి', 'పొట్టపై నిద్రించకండి', 'అకస్మాత్తుగా మెలికలు తిప్పకండి'],
      hi: ['भारी सामान न उठाएं', 'बिना ब्रेक के घंटों न बैठें', 'ऊंची एड़ी न पहनें', 'पेट के बल न सोएं', 'अचानक मुड़ने से बचें'],
    },
    recovery: {
      en: 'With consistent daily yoga practice, most back pain cases show significant improvement in 4–6 weeks. Start with 10 minutes daily and gradually increase to 30 minutes.',
      te: 'నిరంతర యోగా అభ్యాసంతో, చాలా వీపు నొప్పి కేసులు 4-6 వారాల్లో మెరుగుపడతాయి. రోజుకు 10 నిమిషాలతో ప్రారంభించి 30 నిమిషాలకు పెంచండి.',
      hi: 'नियमित योग अभ्यास से, अधिकांश पीठ दर्द के मामलों में 4-6 सप्ताह में सुधार होता है।',
    },
    duration: { weeks: 4, minutes: 20 },
  },
  {
    id: 'neck_pain',
    emoji: '🦒',
    color: '#FB8C00',
    lightColor: '#FFF3E0',
    name: { en: 'Neck Pain', te: 'మెడ నొప్పి', hi: 'गर्दन दर्द' },
    desc: { en: 'Yoga therapy for neck stiffness and pain', te: 'మెడ నొప్పి నివారణకు యోగా', hi: 'गर्दन दर्द के लिए योग चिकित्सा' },
    asanas: [
      {
        id: 'neck_rolls',
        sanskritName: 'Greeva Sanchalana',
        name: { en: 'Neck Rolls (Greeva Sanchalana)', te: 'గ్రీవ సంచలన', hi: 'गर्दन घुमाना' },
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Neck_stretching.jpg/640px-Neck_stretching.jpg',
        duration: { en: '3 min', te: '3 నిమిషాలు', hi: '3 मिनट' },
        steps: {
          en: ['Sit comfortably with spine straight', 'Slowly drop right ear to right shoulder', 'Roll chin to chest, then left ear to left shoulder', 'Complete 5 full circles clockwise', 'Repeat 5 times anti-clockwise'],
          te: ['వెన్నెముక నిటారుగా ఉంచి సుఖంగా కూర్చోండి', 'కుడి చెవిని కుడి భుజానికి మెల్లగా వంచండి', 'గడ్డాన్ని గుండెపైకి వంచి ఎడమవైపుకు తీసుకెళ్ళండి', 'సవ్యదిశలో 5 సార్లు తిప్పండి', 'అపసవ్య దిశలో 5 సార్లు'],
          hi: ['सीधे बैठें, रीढ़ सीधी रखें', 'दाएं कान को दाएं कंधे की तरफ झुकाएं', 'ठुड्डी सीने की तरफ, फिर बाईं ओर', 'दक्षिणावर्त 5 बार घुमाएं', 'वामावर्त 5 बार'],
        },
        benefit: { en: 'Relieves neck stiffness and improves circulation', te: 'మెడ బిగుతును తగ్గిస్తుంది', hi: 'गर्दन की कठोरता दूर होती है' },
      },
      {
        id: 'bitilasana',
        sanskritName: 'Thread the Needle Pose',
        name: { en: 'Thread the Needle Pose', te: 'సూది దారం ఆసన', hi: 'सुई धागा आसन' },
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Thread_the_needle_pose.jpg/640px-Thread_the_needle_pose.jpg',
        duration: { en: '4 min', te: '4 నిమిషాలు', hi: '4 मिनट' },
        steps: {
          en: ['Start on hands and knees', 'Slide right arm under left arm, palm up', 'Lower right shoulder and cheek to mat', 'Keep hips high, breathe deeply', 'Hold 30 seconds each side'],
          te: ['చేతులు మోకాళ్ళపై ప్రారంభించండి', 'కుడి చేయి ఎడమ చేయి కింద జారించండి', 'కుడి భుజం నేలకు ఆనించండి', '30 సెకన్లు ఉండండి', 'ప్రతి వైపు పునరావృతం చేయండి'],
          hi: ['हाथों और घुटनों पर शुरू करें', 'दाएं हाथ को बाएं हाथ के नीचे डालें', 'दाएं कंधे और गाल को जमीन पर रखें', '30 सेकंड दोनों तरफ'],
        },
        benefit: { en: 'Deep stretch for neck and upper back', te: 'మెడ మరియు వీపు సాగుతుంది', hi: 'गर्दन और ऊपरी पीठ में खिंचाव' },
      },
    ],
    foodEat: [
      { name: { en: 'Magnesium-rich foods', te: 'మెగ్నీషియం ఆహారం', hi: 'मैग्नीशियम युक्त खाना' }, image: 'https://images.unsplash.com/photo-1574316071802-0d684efa7bf5?w=200', emoji: '🥦' },
      { name: { en: 'Green Tea', te: 'గ్రీన్ టీ', hi: 'हरी चाय' }, image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=200', emoji: '🍵' },
      { name: { en: 'Almonds', te: 'బాదం పప్పు', hi: 'बादाम' }, image: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=200', emoji: '🌰' },
    ],
    foodAvoid: [
      { name: { en: 'Alcohol', te: 'మద్యం', hi: 'शराब' }, image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=200', emoji: '🍺' },
      { name: { en: 'Excess Caffeine', te: 'అధిక కెఫీన్', hi: 'अधिक कैफीन' }, image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=200', emoji: '☕' },
    ],
    dos: {
      en: ['Use an ergonomic pillow', 'Take screen breaks every 30 minutes', 'Keep monitor at eye level', 'Do neck stretches hourly'],
      te: ['ఎర్గోనామిక్ దిండు వాడండి', 'ప్రతి 30 నిమిషాలకు విరామం తీసుకోండి', 'మానిటర్ కంటి స్థాయిలో ఉంచండి'],
      hi: ['एर्गोनोमिक तकिया उपयोग करें', 'हर 30 मिनट में स्क्रीन ब्रेक लें', 'मॉनिटर आंख के स्तर पर रखें'],
    },
    donts: {
      en: ['Don\'t look down at phone for long', 'Avoid sleeping with neck bent', 'Don\'t carry heavy bags on one shoulder'],
      te: ['ఫోన్ వైపు ఎక్కువసేపు చూడకండి', 'మెడ వంగిన స్థితిలో నిద్రించకండి'],
      hi: ['फोन पर लंबे समय तक न देखें', 'गर्दन मोड़कर न सोएं'],
    },
    recovery: {
      en: 'Neck pain from muscle tension typically improves in 2–3 weeks with regular yoga and proper posture habits.',
      te: 'కండరాల ఉద్రిక్తతవల్ల వచ్చే మెడ నొప్పి సాధారణంగా 2-3 వారాల్లో మెరుగుపడుతుంది.',
      hi: 'मांसपेशियों के तनाव से गर्दन दर्द आमतौर पर 2-3 सप्ताह में ठीक होता है।',
    },
    duration: { weeks: 3, minutes: 15 },
  },
  {
    id: 'diabetes',
    emoji: '🩺',
    color: '#1565C0',
    lightColor: '#E3F2FD',
    name: { en: 'Diabetes', te: 'మధుమేహం', hi: 'मधुमेह' },
    desc: { en: 'Yoga to manage blood sugar levels naturally', te: 'రక్తంలో చక్కెర స్థాయిలను నియంత్రించే యోగా', hi: 'रक्त शर्करा को प्राकृतिक रूप से नियंत्रित करें' },
    asanas: [
      {
        id: 'dhanurasana',
        sanskritName: 'Dhanurasana',
        name: { en: 'Bow Pose (Dhanurasana)', te: 'ధనురాసన', hi: 'धनुरासन' },
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Dhanurasana_Yoga-Asana_Nina-Mel.jpg/640px-Dhanurasana_Yoga-Asana_Nina-Mel.jpg',
        duration: { en: '3 min', te: '3 నిమిషాలు', hi: '3 मिनट' },
        steps: {
          en: ['Lie on stomach, bend knees', 'Reach back and hold ankles', 'Inhale — lift chest and thighs off floor', 'Hold for 20–30 seconds', 'Exhale and release slowly'],
          te: ['పొట్టపై పడుకుని మోకాళ్ళు వంచండి', 'వెనక్కి చేయి చాచి చీళ్ళు పట్టుకోండి', 'శ్వాస తీసుకుంటూ గుండె మరియు తొడలు పైకి ఎత్తండి', '20-30 సెకన్లు ఉండండి'],
          hi: ['पेट के बल लेटें, घुटने मोड़ें', 'पीछे हाथ बढ़ाकर टखने पकड़ें', 'सांस लेते हुए सीना और जांघें उठाएं', '20-30 सेकंड रहें'],
        },
        benefit: { en: 'Stimulates pancreas, helps control blood sugar', te: 'అగ్న్యాశయాన్ని ఉత్తేజపరుస్తుంది', hi: 'अग्न्याशय को उत्तेजित करता है' },
      },
      {
        id: 'paschimottanasana',
        sanskritName: 'Paschimottanasana',
        name: { en: 'Seated Forward Bend (Paschimottanasana)', te: 'పశ్చిమోత్తానాసన', hi: 'पश्चिमोत्तानासन' },
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Paschimottanasana_Yoga-Asana_Nina-Mel.jpg/640px-Paschimottanasana_Yoga-Asana_Nina-Mel.jpg',
        duration: { en: '4 min', te: '4 నిమిషాలు', hi: '4 मिनट' },
        steps: {
          en: ['Sit with legs extended straight', 'Inhale — raise arms overhead', 'Exhale — fold forward from hips', 'Hold feet or shins, relax head down', 'Hold 1–3 minutes, breathe deeply'],
          te: ['కాళ్ళు నేరుగా చాచి కూర్చోండి', 'శ్వాస తీసుకుంటూ చేతులు పైకి ఎత్తండి', 'శ్వాస వదులుతూ ముందుకు వంగండి', '1-3 నిమిషాలు ఉండండి'],
          hi: ['पैर सीधे फैलाकर बैठें', 'सांस लेते हुए हाथ ऊपर उठाएं', 'सांस छोड़ते हुए आगे झुकें', '1-3 मिनट रहें'],
        },
        benefit: { en: 'Massages abdominal organs, regulates blood sugar', te: 'ఉదర అవయవాలకు మసాజ్ చేస్తుంది', hi: 'पेट के अंगों की मालिश करता है' },
      },
    ],
    foodEat: [
      { name: { en: 'Bitter Gourd', te: 'కారేల', hi: 'करेला' }, image: 'https://images.unsplash.com/photo-1567375698348-5d9d5ae99de0?w=200', emoji: '🥒' },
      { name: { en: 'Fenugreek', te: 'మేంతులు', hi: 'मेथी' }, image: 'https://images.unsplash.com/photo-1559181567-c3190bfa4655?w=200', emoji: '🌿' },
      { name: { en: 'Whole Grains', te: 'తృణధాన్యాలు', hi: 'साबुत अनाज' }, image: 'https://images.unsplash.com/photo-1542444459-b09cb16f2a23?w=200', emoji: '🌾' },
      { name: { en: 'Cinnamon', te: 'దాల్చిన చెక్క', hi: 'दालचीनी' }, image: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?w=200', emoji: '🪵' },
    ],
    foodAvoid: [
      { name: { en: 'White Rice', te: 'తెల్ల బియ్యం', hi: 'सफेद चावल' }, image: 'https://images.unsplash.com/photo-1536304993881-ff86e0c9bbe9?w=200', emoji: '🍚' },
      { name: { en: 'Sweets', te: 'తీపి పదార్థాలు', hi: 'मिठाई' }, image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=200', emoji: '🍬' },
      { name: { en: 'Fruit Juices', te: 'పండ్ల రసాలు', hi: 'फलों का रस' }, image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=200', emoji: '🍹' },
    ],
    dos: {
      en: ['Check blood sugar daily', 'Exercise 30 minutes daily', 'Eat small frequent meals', 'Stay hydrated', 'Sleep 7-8 hours'],
      te: ['రక్తంలో చక్కెరను రోజు తనిఖీ చేయండి', 'రోజుకు 30 నిమిషాలు వ్యాయామం చేయండి', 'చిన్న చిన్న భోజనాలు తరచుగా తినండి'],
      hi: ['रोज रक्त शर्करा जांचें', 'रोज 30 मिनट व्यायाम करें', 'थोड़ा-थोड़ा बार-बार खाएं'],
    },
    donts: {
      en: ['Avoid skipping meals', 'Don\'t eat large portions', 'Avoid sugary drinks', 'Don\'t sit idle for hours'],
      te: ['భోజనం skip చేయకండి', 'పెద్ద పరిమాణాలలో తినకండి', 'తీపి పానీయాలు తాగకండి'],
      hi: ['खाना न छोड़ें', 'बड़े हिस्से न खाएं', 'मीठे पेय से बचें'],
    },
    recovery: {
      en: 'Yoga combined with dietary changes can help stabilize blood sugar levels within 8–12 weeks. Always consult your doctor for medication adjustments.',
      te: 'యోగా మరియు ఆహార మార్పులతో రక్తంలో చక్కెర స్థాయిలు 8-12 వారాల్లో స్థిరపడవచ్చు.',
      hi: 'योग और आहार परिवर्तन से 8-12 सप्ताह में रक्त शर्करा स्थिर हो सकती है।',
    },
    duration: { weeks: 8, minutes: 30 },
  },
  {
    id: 'high_bp',
    emoji: '❤️',
    color: '#C62828',
    lightColor: '#FFEBEE',
    name: { en: 'High BP', te: 'అధిక రక్తపోటు', hi: 'उच्च रक्तचाप' },
    desc: { en: 'Gentle yoga to lower blood pressure naturally', te: 'రక్తపోటు తగ్గించే మృదువైన యోగా', hi: 'रक्तचाप को कम करने के लिए योग' },
    asanas: [
      {
        id: 'shavasana',
        sanskritName: 'Shavasana',
        name: { en: 'Corpse Pose (Shavasana)', te: 'శవాసన', hi: 'शवासन' },
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Shavasana_2.jpg/640px-Shavasana_2.jpg',
        duration: { en: '10 min', te: '10 నిమిషాలు', hi: '10 मिनट' },
        steps: {
          en: ['Lie flat on your back', 'Arms at sides, palms facing up', 'Close eyes, relax every muscle', 'Focus only on your breathing', 'Stay for 10–15 minutes'],
          te: ['వెల్లకిలా పడుకోండి', 'చేతులు ప్రక్కన, అరచేతులు పైకి', 'కళ్ళు మూసి ప్రతి కండరాన్ని రిలాక్స్ చేయండి', 'శ్వాసపై మాత్రమే దృష్టి ఉంచండి', '10-15 నిమిషాలు ఉండండి'],
          hi: ['पीठ के बल सीधे लेटें', 'हाथ बगल में, हथेलियां ऊपर', 'आंखें बंद करें, हर मांसपेशी ढीली करें', 'केवल सांस पर ध्यान दें', '10-15 मिनट रहें'],
        },
        benefit: { en: 'Deeply relaxes nervous system, lowers blood pressure', te: 'నాడీ వ్యవస్థను రిలాక్స్ చేస్తుంది', hi: 'तंत्रिका तंत्र को गहराई से आराम देता है' },
      },
      {
        id: 'anulom_vilom',
        sanskritName: 'Pranayama',
        name: { en: 'Alternate Nostril Breathing (Anulom Vilom)', te: 'అనులోమ విలోమ', hi: 'अनुलोम विलोम' },
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Pranayama.jpg/640px-Pranayama.jpg',
        duration: { en: '5 min', te: '5 నిమిషాలు', hi: '5 मिनट' },
        steps: {
          en: ['Sit comfortably, spine straight', 'Close right nostril with thumb, inhale left', 'Close left nostril, exhale right', 'Inhale right, close right, exhale left', 'Continue for 5–10 minutes'],
          te: ['సుఖంగా కూర్చుని వెన్నెముక నిటారుగా ఉంచండి', 'కుడి నాసిక మూసి ఎడమతో శ్వాస తీసుకోండి', 'ఎడమ మూసి కుడితో వదలండి', '5-10 నిమిషాలు కొనసాగించండి'],
          hi: ['आरामदायक स्थिति में बैठें', 'दाएं नाक को बंद करें, बाएं से सांस लें', 'बाएं बंद करें, दाएं से छोड़ें', '5-10 मिनट जारी रखें'],
        },
        benefit: { en: 'Balances nervous system, reduces stress and BP', te: 'నాడీ వ్యవస్థను సమతుల్యం చేస్తుంది', hi: 'तंत्रिका तंत्र को संतुलित करता है' },
      },
    ],
    foodEat: [
      { name: { en: 'Banana', te: 'అరటి పండు', hi: 'केला' }, image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=200', emoji: '🍌' },
      { name: { en: 'Garlic', te: 'వెల్లుల్లి', hi: 'लहसुन' }, image: 'https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?w=200', emoji: '🧄' },
      { name: { en: 'Leafy Greens', te: 'ఆకుకూరలు', hi: 'हरी पत्तेदार सब्जियां' }, image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=200', emoji: '🥬' },
    ],
    foodAvoid: [
      { name: { en: 'Salt', te: 'ఉప్పు', hi: 'नमक' }, image: 'https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?w=200', emoji: '🧂' },
      { name: { en: 'Red Meat', te: 'ఎర్ర మాంసం', hi: 'लाल मांस' }, image: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=200', emoji: '🥩' },
      { name: { en: 'Alcohol', te: 'మద్యం', hi: 'शराब' }, image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=200', emoji: '🍺' },
    ],
    dos: {
      en: ['Monitor BP twice daily', 'Practice deep breathing 10 min daily', 'Walk 30 minutes morning', 'Reduce stress with meditation', 'Take prescribed medication regularly'],
      te: ['రోజుకు రెండుసార్లు BP తనిఖీ చేయండి', 'రోజు 10 నిమిషాలు లోతైన శ్వాస తీసుకోండి', 'ఉదయం 30 నిమిషాలు నడవండి'],
      hi: ['दिन में दो बार BP जांचें', 'रोज 10 मिनट गहरी सांस लें', 'सुबह 30 मिनट टहलें'],
    },
    donts: {
      en: ['Avoid intense exercise', 'Don\'t eat too much salt', 'Avoid stress and anger', 'Don\'t skip BP medication', 'Avoid inverted yoga poses'],
      te: ['తీవ్రమైన వ్యాయామం చేయకండి', 'ఎక్కువ ఉప్పు తినకండి', 'ఒత్తిడి మరియు కోపం మానండి'],
      hi: ['तीव्र व्यायाम से बचें', 'अधिक नमक न खाएं', 'तनाव और गुस्से से बचें'],
    },
    recovery: {
      en: 'Gentle yoga and lifestyle changes can show BP reduction in 6–8 weeks. Never stop medication without doctor\'s advice.',
      te: 'మృదువైన యోగా మరియు జీవనశైలి మార్పులు 6-8 వారాల్లో BP తగ్గించవచ్చు.',
      hi: 'सौम्य योग और जीवनशैली बदलाव से 6-8 सप्ताह में BP कम हो सकता है।',
    },
    duration: { weeks: 6, minutes: 20 },
  },
  {
    id: 'stress',
    emoji: '🧠',
    color: '#6A1B9A',
    lightColor: '#F3E5F5',
    name: { en: 'Stress & Anxiety', te: 'ఒత్తిడి & ఆందోళన', hi: 'तनाव और चिंता' },
    desc: { en: 'Calming yoga and breathwork for mental peace', te: 'మానసిక శాంతికి శాంతదాయక యోగా', hi: 'मानसिक शांति के लिए योग' },
    asanas: [
      {
        id: 'viparita_karani',
        sanskritName: 'Viparita Karani',
        name: { en: 'Legs Up The Wall (Viparita Karani)', te: 'విపరీత కరణి', hi: 'विपरीत करणी' },
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Viparita_Karani_Yoga-Asana_Nina-Mel.jpg/640px-Viparita_Karani_Yoga-Asana_Nina-Mel.jpg',
        duration: { en: '10 min', te: '10 నిమిషాలు', hi: '10 मिनट' },
        steps: {
          en: ['Sit sideways next to a wall', 'Swing legs up as you lie back', 'Rest legs against wall, body flat', 'Arms at sides, eyes closed', 'Stay 5–15 minutes, breathe slowly'],
          te: ['గోడ పక్కన ప్రక్కగా కూర్చోండి', 'వెల్లకిలా పడుతూ కాళ్ళు పైకి ఎత్తండి', 'కాళ్ళు గోడకు ఆనించండి', '5-15 నిమిషాలు ఉండండి'],
          hi: ['दीवार के पास बैठें', 'पैर दीवार पर उठाते हुए लेटें', '5-15 मिनट रहें, धीरे-धीरे सांस लें'],
        },
        benefit: { en: 'Instantly calms nervous system and reduces anxiety', te: 'నాడీ వ్యవస్థను వెంటనే శాంతింపజేస్తుంది', hi: 'तंत्रिका तंत्र को तुरंत शांत करता है' },
      },
    ],
    foodEat: [
      { name: { en: 'Dark Chocolate', te: 'డార్క్ చాకొలేట్', hi: 'डार्क चॉकलेट' }, image: 'https://images.unsplash.com/photo-1575377222312-dd1a63a51638?w=200', emoji: '🍫' },
      { name: { en: 'Chamomile Tea', te: 'కేమొమైల్ టీ', hi: 'कैमोमाइल चाय' }, image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=200', emoji: '🍵' },
      { name: { en: 'Blueberries', te: 'బ్లూబెర్రీలు', hi: 'ब्लूबेरी' }, image: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=200', emoji: '🫐' },
    ],
    foodAvoid: [
      { name: { en: 'Caffeine', te: 'కెఫీన్', hi: 'कैफीन' }, image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=200', emoji: '☕' },
      { name: { en: 'Alcohol', te: 'మద్యం', hi: 'शराब' }, image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=200', emoji: '🍺' },
    ],
    dos: {
      en: ['Meditate 10 minutes daily', 'Journal your thoughts', 'Spend time in nature', 'Talk to a trusted person', 'Practice gratitude daily'],
      te: ['రోజు 10 నిమిషాలు ధ్యానం చేయండి', 'మీ ఆలోచనలు రాయండి', 'ప్రకృతిలో సమయం గడపండి'],
      hi: ['रोज 10 मिनट ध्यान करें', 'अपने विचार लिखें', 'प्रकृति में समय बिताएं'],
    },
    donts: {
      en: ['Avoid news overload', 'Don\'t isolate yourself', 'Avoid excessive screen time', 'Don\'t suppress emotions'],
      te: ['వార్తలు ఎక్కువగా చూడకండి', 'ఒంటరిగా ఉండకండి', 'స్క్రీన్ టైమ్ తగ్గించండి'],
      hi: ['अधिक समाचार न देखें', 'अकेले न रहें', 'स्क्रीन टाइम कम करें'],
    },
    recovery: {
      en: 'With daily yoga and mindfulness practice, anxiety levels typically reduce significantly within 3–4 weeks.',
      te: 'రోజువారీ యోగా మరియు మైండ్‌ఫుల్‌నెస్‌తో, 3-4 వారాల్లో ఆందోళన గణనీయంగా తగ్గుతుంది.',
      hi: 'रोज योग और माइंडफुलनेस से 3-4 सप्ताह में चिंता काफी कम हो जाती है।',
    },
    duration: { weeks: 4, minutes: 15 },
  },
  {
    id: 'headache',
    emoji: '🤕',
    color: '#00695C',
    lightColor: '#E0F2F1',
    name: { en: 'Headache / Migraine', te: 'తలనొప్పి / మైగ్రేన్', hi: 'सिरदर्द / माइग्रेन' },
    desc: { en: 'Yoga poses to relieve headaches and migraines', te: 'తలనొప్పి నివారణకు యోగా', hi: 'सिरदर्द से राहत के लिए योग' },
    asanas: [
      {
        id: 'uttanasana',
        sanskritName: 'Uttanasana',
        name: { en: 'Standing Forward Fold (Uttanasana)', te: 'ఉత్తానాసన', hi: 'उत्तानासन' },
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Uttanasana_Yoga-Asana_Nina-Mel.jpg/640px-Uttanasana_Yoga-Asana_Nina-Mel.jpg',
        duration: { en: '3 min', te: '3 నిమిషాలు', hi: '3 मिनट' },
        steps: {
          en: ['Stand with feet hip-width apart', 'Inhale — lengthen spine', 'Exhale — fold forward from hips', 'Let head hang heavy', 'Hold knees or let arms dangle for 1-3 min'],
          te: ['పాదాలు మూపులు వెడల్పుగా నిలబడండి', 'శ్వాస తీసుకుంటూ వెన్నెముక పొడవు చేయండి', 'శ్వాస వదులుతూ ముందుకు వంగండి', '1-3 నిమిషాలు ఉండండి'],
          hi: ['कूल्हे-चौड़ाई पर खड़े हों', 'सांस लेते हुए रीढ़ लंबी करें', 'सांस छोड़ते हुए आगे झुकें', '1-3 मिनट रहें'],
        },
        benefit: { en: 'Increases blood flow to brain, relieves tension headaches', te: 'మెదడుకు రక్త ప్రసరణ పెరుగుతుంది', hi: 'मस्तिष्क में रक्त प्रवाह बढ़ाता है' },
      },
    ],
    foodEat: [
      { name: { en: 'Water', te: 'నీరు', hi: 'पानी' }, image: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=200', emoji: '💧' },
      { name: { en: 'Ginger', te: 'అల్లం', hi: 'अदरक' }, image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=200', emoji: '🫚' },
      { name: { en: 'Magnesium foods', te: 'మెగ్నీషియం ఆహారాలు', hi: 'मैग्नीशियम खाद्य पदार्थ' }, image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=200', emoji: '🥜' },
    ],
    foodAvoid: [
      { name: { en: 'Aged Cheese', te: 'పాత చీజ్', hi: 'पुराना पनीर' }, image: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a2d4?w=200', emoji: '🧀' },
      { name: { en: 'Alcohol', te: 'మద్యం', hi: 'शराब' }, image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=200', emoji: '🍷' },
    ],
    dos: {
      en: ['Stay well hydrated', 'Maintain regular sleep schedule', 'Practice yoga in dim light', 'Use lavender oil for temples'],
      te: ['బాగా నీరు త్రాగండి', 'నిరంతర నిద్ర వేళపాలు పాటించండి', 'లావెండర్ నూనె నొసటిపై రాయండి'],
      hi: ['खूब पानी पिएं', 'नियमित नींद का समय रखें', 'लैवेंडर तेल कनपटी पर लगाएं'],
    },
    donts: {
      en: ['Avoid bright lights during migraine', 'Don\'t skip meals', 'Avoid strong smells', 'Don\'t stare at screens too long'],
      te: ['మైగ్రేన్ సమయంలో తేజస్సు వెలుతురు మానండి', 'భోజనం skip చేయకండి'],
      hi: ['माइग्रेन में तेज रोशनी से बचें', 'खाना न छोड़ें'],
    },
    recovery: {
      en: 'Regular yoga practice reduces headache frequency by 50% in most people within 6 weeks.',
      te: 'నిరంతర యోగా అభ్యాసం 6 వారాల్లో తలనొప్పి పౌనఃపున్యాన్ని 50% తగ్గిస్తుంది.',
      hi: 'नियमित योग से 6 सप्ताह में सिरदर्द की आवृत्ति 50% कम होती है।',
    },
    duration: { weeks: 6, minutes: 20 },
  },
  {
    id: 'knee_pain',
    emoji: '🦵',
    color: '#2E7D32',
    lightColor: '#E8F5E9',
    name: { en: 'Knee Pain', te: 'మోకాలి నొప్పి', hi: 'घुटने का दर्द' },
    desc: { en: 'Gentle yoga to strengthen knees and reduce pain', te: 'మోకాళ్ళను బలపరిచే మృదువైన యోగా', hi: 'घुटनों को मजबूत बनाने के लिए योग' },
    asanas: [
      {
        id: 'virasana',
        sanskritName: 'Virasana',
        name: { en: 'Hero Pose (Virasana)', te: 'వీరాసన', hi: 'वीरासन' },
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Virasana_Yoga-Asana_Nina-Mel.jpg/640px-Virasana_Yoga-Asana_Nina-Mel.jpg',
        duration: { en: '3 min', te: '3 నిమిషాలు', hi: '3 मिनट' },
        steps: {
          en: ['Kneel on the floor, knees together', 'Sit back between your heels', 'Place hands on thighs', 'Keep spine upright, breathe deeply', 'Hold 1-3 minutes'],
          te: ['నేలపై మోకాళ్ళు వేసి కూర్చోండి', 'కాళ్ళ మధ్య కూర్చోండి', 'చేతులు తొడలపై ఉంచండి', '1-3 నిమిషాలు ఉండండి'],
          hi: ['फर्श पर घुटनों के बल बैठें', 'एड़ियों के बीच बैठें', 'हाथ जांघों पर रखें', '1-3 मिनट रहें'],
        },
        benefit: { en: 'Stretches knee joints and improves flexibility', te: 'మోకాలి కీళ్ళను సాగదీస్తుంది', hi: 'घुटने के जोड़ों को खींचता है' },
      },
    ],
    foodEat: [
      { name: { en: 'Turmeric', te: 'పసుపు', hi: 'हल्दी' }, image: 'https://images.unsplash.com/photo-1615485500704-8e3b85efb8f0?w=200', emoji: '🟡' },
      { name: { en: 'Omega-3 Foods', te: 'ఒమేగా-3 ఆహారాలు', hi: 'ओमेगा-3 खाद्य पदार्थ' }, image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=200', emoji: '🐟' },
    ],
    foodAvoid: [
      { name: { en: 'Processed Foods', te: 'ప్రాసెస్ ఆహారం', hi: 'प्रसंस्कृत भोजन' }, image: 'https://images.unsplash.com/photo-1527459822135-9a2a6c399f3f?w=200', emoji: '🍕' },
      { name: { en: 'Sugary Drinks', te: 'తీపి పానీయాలు', hi: 'मीठे पेय' }, image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=200', emoji: '🥤' },
    ],
    dos: {
      en: ['Strengthen quadriceps with gentle exercises', 'Use knee support when needed', 'Maintain healthy weight', 'Swim or cycle instead of running'],
      te: ['తేలికైన వ్యాయామాలతో తొడ కండరాలు బలపరచండి', 'అవసరమైతే మోకాలి సపోర్ట్ వాడండి'],
      hi: ['हल्के व्यायाम से जांघ की मांसपेशियां मजबूत करें', 'जरूरत पर घुटने का सहारा उपयोग करें'],
    },
    donts: {
      en: ['Avoid deep squats', 'Don\'t run on hard surfaces', 'Avoid kneeling for long', 'Don\'t ignore pain signals'],
      te: ['లోతైన స్క్వాట్లు చేయకండి', 'గట్టి నేలలపై పరిగెత్తకండి'],
      hi: ['गहरे स्क्वैट्स से बचें', 'कठोर सतह पर न दौड़ें'],
    },
    recovery: {
      en: 'Gentle yoga strengthening exercises show improvement in knee pain within 4-6 weeks of consistent practice.',
      te: 'మృదువైన యోగా బలపరిచే వ్యాయామాలు 4-6 వారాల్లో మోకాలి నొప్పిలో మెరుగుదల చూపిస్తాయి.',
      hi: 'सौम्य योग से 4-6 सप्ताह में घुटने के दर्द में सुधार होता है।',
    },
    duration: { weeks: 5, minutes: 20 },
  },
  {
    id: 'pcod',
    emoji: '🌸',
    color: '#AD1457',
    lightColor: '#FCE4EC',
    name: { en: 'PCOD / PCOS', te: 'పీసీఓడీ', hi: 'पीसीओडी' },
    desc: { en: 'Yoga therapy for hormonal balance and PCOD relief', te: 'హార్మోనల్ సమతుల్యత కోసం యోగా', hi: 'हार्मोनल संतुलन के लिए योग' },
    asanas: [
      {
        id: 'baddha_konasana',
        sanskritName: 'Baddha Konasana',
        name: { en: 'Butterfly Pose (Baddha Konasana)', te: 'బద్ధ కోణాసన', hi: 'बद्ध कोणासन' },
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Bound_angle_pose.jpg/640px-Bound_angle_pose.jpg',
        duration: { en: '5 min', te: '5 నిమిషాలు', hi: '5 मिनट' },
        steps: {
          en: ['Sit with spine straight', 'Bring soles of feet together', 'Hold feet with both hands', 'Gently flap knees up and down', 'Hold still for 1-3 minutes'],
          te: ['వెన్నెముక నిటారుగా కూర్చోండి', 'రెండు పాదాలు ఒకదానితో ఒకటి కలపండి', 'చేతులతో పాదాలు పట్టుకోండి', 'మోకాళ్ళు పైకి కిందకు ఊపండి', '1-3 నిమిషాలు ఉండండి'],
          hi: ['सीधे बैठें', 'पैरों के तलवे मिलाएं', 'हाथों से पैर पकड़ें', 'घुटनों को ऊपर-नीचे हिलाएं', '1-3 मिनट रहें'],
        },
        benefit: { en: 'Stimulates ovaries, improves blood flow to pelvis', te: 'అండాశయాలను ఉత్తేజపరుస్తుంది', hi: 'अंडाशय को उत्तेजित करता है' },
      },
    ],
    foodEat: [
      { name: { en: 'Flax Seeds', te: 'అవిసె గింజలు', hi: 'अलसी के बीज' }, image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200', emoji: '🌱' },
      { name: { en: 'Cinnamon', te: 'దాల్చిన చెక్క', hi: 'दालचीनी' }, image: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?w=200', emoji: '🪵' },
      { name: { en: 'Green Vegetables', te: 'పచ్చి కూరగాయలు', hi: 'हरी सब्जियां' }, image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=200', emoji: '🥦' },
    ],
    foodAvoid: [
      { name: { en: 'Dairy', te: 'పాల ఉత్పత్తులు', hi: 'डेयरी उत्पाद' }, image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=200', emoji: '🥛' },
      { name: { en: 'Refined Sugar', te: 'శుద్ధి చేసిన పంచదార', hi: 'परिष्कृत चीनी' }, image: 'https://images.unsplash.com/photo-1584358832987-f92ef2c4a71f?w=200', emoji: '🍬' },
    ],
    dos: {
      en: ['Exercise 30-40 minutes daily', 'Manage stress through yoga', 'Maintain healthy weight', 'Track menstrual cycle', 'Consult gynecologist regularly'],
      te: ['రోజుకు 30-40 నిమిషాలు వ్యాయామం చేయండి', 'యోగా ద్వారా ఒత్తిడిని నిర్వహించండి', 'స్త్రీ వైద్యుడిని క్రమం తప్పకుండా సంప్రదించండి'],
      hi: ['रोज 30-40 मिनट व्यायाम करें', 'योग से तनाव प्रबंधन करें', 'नियमित स्त्री रोग विशेषज्ञ से मिलें'],
    },
    donts: {
      en: ['Avoid processed and junk food', 'Don\'t skip meals', 'Avoid stress', 'Don\'t ignore irregular periods'],
      te: ['ప్రాసెస్ చేసిన ఆహారం మానండి', 'భోజనం skip చేయకండి', 'అనియమిత రుతుచక్రాన్ని పట్టించుకోకపోవద్దు'],
      hi: ['जंक फूड से बचें', 'खाना न छोड़ें', 'अनियमित मासिक धर्म को नजरअंदाज न करें'],
    },
    recovery: {
      en: 'Consistent yoga and dietary changes can help regulate hormones and improve PCOD symptoms within 3-6 months.',
      te: 'నిరంతర యోగా మరియు ఆహార మార్పులతో 3-6 నెలల్లో PCOD లక్షణాలు మెరుగుపడవచ్చు.',
      hi: 'नियमित योग और आहार बदलाव से 3-6 महीनों में PCOD के लक्षण सुधर सकते हैं।',
    },
    duration: { weeks: 12, minutes: 30 },
  },
  {
    id: 'shoulder_pain',
    emoji: '💪',
    color: '#E65100',
    lightColor: '#FBE9E7',
    name: { en: 'Shoulder Pain', te: 'భుజం నొప్పి', hi: 'कंधे का दर्द' },
    desc: { en: 'Yoga to relieve shoulder tension and pain', te: 'భుజం నొప్పి నివారణకు యోగా', hi: 'कंधे के दर्द से राहत के लिए योग' },
    asanas: [
      {
        id: 'garudasana_arms',
        sanskritName: 'Garudasana',
        name: { en: 'Eagle Arms (Garudasana Arms)', te: 'గరుడాసన చేతులు', hi: 'गरुड़ासन भुजाएं' },
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Garudasana_Yoga-Asana_Nina-Mel.jpg/640px-Garudasana_Yoga-Asana_Nina-Mel.jpg',
        duration: { en: '3 min', te: '3 నిమిషాలు', hi: '3 मिनट' },
        steps: {
          en: ['Sit or stand comfortably', 'Extend arms forward, cross right over left', 'Bend elbows and wrap forearms', 'Lift elbows to shoulder height', 'Hold 30 seconds, switch sides'],
          te: ['సుఖంగా కూర్చోండి లేదా నిలబడండి', 'చేతులు ముందుకు చాచి కుడిని ఎడమపై వేయండి', 'మోచేతులు వంచి ముందు భాగాలను చుట్టండి', '30 సెకన్లు ఉండి మార్చండి'],
          hi: ['आरामदायक स्थिति में बैठें या खड़े हों', 'हाथ आगे फैलाएं, दाएं को बाएं पर रखें', 'कोहनियां मोड़ें', '30 सेकंड रोकें, दूसरी तरफ करें'],
        },
        benefit: { en: 'Stretches shoulder joints and upper back', te: 'భుజం కీళ్ళను సాగదీస్తుంది', hi: 'कंधे के जोड़ों को खींचता है' },
      },
    ],
    foodEat: [
      { name: { en: 'Turmeric', te: 'పసుపు', hi: 'हल्दी' }, image: 'https://images.unsplash.com/photo-1615485500704-8e3b85efb8f0?w=200', emoji: '🟡' },
      { name: { en: 'Fish', te: 'చేపలు', hi: 'मछली' }, image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=200', emoji: '🐟' },
    ],
    foodAvoid: [
      { name: { en: 'Inflammatory Foods', te: 'వాపు కలిగించే ఆహారాలు', hi: 'सूजन पैदा करने वाले खाद्य पदार्थ' }, image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=200', emoji: '🍟' },
    ],
    dos: {
      en: ['Do shoulder rotations every hour', 'Use ergonomic chair', 'Apply heat before exercise', 'Strengthen rotator cuff muscles'],
      te: ['ప్రతి గంటా భుజం తిప్పడం చేయండి', 'ఎర్గోనామిక్ కుర్చీ వాడండి', 'వ్యాయామానికి ముందు వేడి వాడండి'],
      hi: ['हर घंटे कंधे घुमाएं', 'एर्गोनोमिक कुर्सी उपयोग करें', 'व्यायाम से पहले गर्म सेंक लगाएं'],
    },
    donts: {
      en: ['Avoid overhead heavy lifting', 'Don\'t sleep on painful shoulder', 'Avoid repetitive arm movements'],
      te: ['తల పైన భారమైన వస్తువులు ఎత్తకండి', 'నొప్పి వచ్చే భుజంపై నిద్రించకండి'],
      hi: ['सिर के ऊपर भारी सामान न उठाएं', 'दर्द वाले कंधे पर न सोएं'],
    },
    recovery: {
      en: 'Shoulder pain from muscle tension usually resolves in 3-4 weeks with consistent yoga and rest.',
      te: 'కండరాల ఉద్రిక్తతవల్ల వచ్చే భుజం నొప్పి సాధారణంగా 3-4 వారాల్లో తగ్గుతుంది.',
      hi: 'मांसपेशियों के तनाव से कंधे का दर्द 3-4 सप्ताह में ठीक होता है।',
    },
    duration: { weeks: 4, minutes: 15 },
  },
];